Module7 task2
htmlacademy-react/217599-six-cities-9 pull request #9
Opened 2022-03-14 18:35 UTC by Shirokuiu

2022-03-14 20:51 UTC, KletskovG requested changes
Есть пара моментов, которые можно улучшить

2022-03-14 20:51 UTC, KletskovG commented on project/src/components/pages/login-page/helpers/build-default-form.ts
> +export const buildDefaultForm = (): LoginPageFormBody => DEFAULT_FORM;
Чтобы не писать подобные конструкции я тебе рекомендую попробовать `readonly` из TS - эта штука как раз и защищает от мутаций

```ts
type LoginPageFormBody = {
 readonly email: string;
 readonly password: string;
}


const DEFAULT_FORM: LoginPageFormBody = {
 email: '',
 password: '',
}

DEFAULT_FORM.email = 'test' // error TS2540: Cannot assign to 'email' because it is a read-only property.
```

Если тип LoginPageFormBody тебе понадобится в будущем для объектов, которые ты захочешь изменить, то ты можешь записать вот таким образом

```ts
const DEFAULT_FORM: Readonly<LoginPageFormBody> = {}
```

`Readonly<T>` - делает все поля только readonly

2022-03-14 20:51 UTC, KletskovG commented on project/src/components/pages/login-page/helpers/make-password-error-msg.ts
> +  let messages: string[] = [];
message можно сразу сделать Set, чтобы там были только уникальные значения

```ts
let messages = new Set<string>([])
```

2022-03-14 20:51 UTC, KletskovG commented on project/src/components/pages/login-page/helpers/make-password-error-msg.ts
> +    messages.push('Введите хотя бы одно число');
Тут делаем просто  (Код примерный)
`messages.add('.... ')`

Очистка после этого не понадобится

2022-03-14 20:51 UTC, KletskovG commented on project/src/components/pages/login-page/helpers/make-password-error-msg.ts
> +    messages.push('Введите хотя бы одну латинскую букву');
Тут тоже самое

2022-03-14 20:51 UTC, KletskovG commented on project/src/components/pages/login-page/helpers/make-password-error-msg.ts
> +  return messages.join('. ');
И в итоге получаем 
`return [...messages].join('. ');`

2022-03-15 16:47 UTC, Shirokuiu commented on project/src/components/pages/login-page/helpers/build-default-form.ts
> +export const buildDefaultForm = (): LoginPageFormBody => DEFAULT_FORM;
`const DEFAULT_FORM: Readonly<LoginPageFormBody> = {}`

Выдает ошибку - `TS2739: Type '{}' is missing the following properties from type 'Readonly ': email, password`

2022-03-16 15:14 UTC, merged